# Azure DevOps Pipeline for Web ChatBot
trigger:
  branches:
    include:
    - main
    - develop

variables:
  pythonVersion: '3.11'
  azureServiceConnection: 'AzureServiceConnection'
  webAppName: 'webchatbot-app'
  resourceGroupName: 'webchatbot-rg'

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    
    - script: |
        python -m pytest tests/ -v
      displayName: 'Run tests'
      continueOnError: true
    
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-results.xml'
        testRunTitle: 'Python Tests'
    
    - script: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      displayName: 'Lint with flake8'
      continueOnError: true

- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployJob
    displayName: Deploy to Azure App Service
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/**/*.zip'
              deploymentMethod: 'zipDeploy'
