name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: webchatbot-app
  AZURE_WEBAPP_PACKAGE_PATH: './webchatbot.zip'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 'Run tests'
      run: |
        python -m pytest tests/ -v
      continue-on-error: true
      
    - name: 'Create deployment package'
      run: |
        zip -r webchatbot.zip . -x "*.git*" "*.pyc" "__pycache__/*" "*.env*" "chroma_db/*" "logs/*"
        
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: 'Configure App Settings'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
            ENVIRONMENT=production \
            DEBUG=false \
            WEBSITES_PORT=8000 \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true
