# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - jrc-enquiry-assistant-operations

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C91D4166D48941858A403CD9242162B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23597B7E33734F0E99075C285D0FF5A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_518ACEC4D46F4C6FBB9B98316C1FCF9E }}

      - name: 'Configure Azure App Settings'
        run: |
          # Verify Azure login
          echo "Checking Azure authentication..."
          az account show
          
          # List all web apps to find the correct one
          echo "Searching for web app: jrc-enquiry-assistant-operations"
          az webapp list --query "[?name=='jrc-enquiry-assistant-operations'].{name:name, resourceGroup:resourceGroup}" --output table
          
          # Get the resource group name for the web app
          RESOURCE_GROUP=$(az webapp list --query "[?name=='jrc-enquiry-assistant-operations'].resourceGroup" --output tsv)
          
          if [ -z "$RESOURCE_GROUP" ]; then
            echo "Web app 'jrc-enquiry-assistant-operations' not found. Available web apps:"
            az webapp list --query "[].{name:name, resourceGroup:resourceGroup}" --output table
            echo "Skipping app settings configuration."
            exit 0
          fi
          
          echo "Found App Service in Resource Group: $RESOURCE_GROUP"
          
          # Stop the app service to prevent conflicts
          echo "Stopping App Service to prevent conflicts..."
          az webapp stop --resource-group $RESOURCE_GROUP --name jrc-enquiry-assistant-operations --slot Production || echo "App service was already stopped"
          
          # Configure app settings
          echo "Configuring App Settings..."
          az webapp config appsettings set --resource-group $RESOURCE_GROUP --name jrc-enquiry-assistant-operations --slot Production --settings \
            WEBSITES_ENABLE_APP_SERVICE_STORAGE=true \
            WEBSITES_PORT=8000 \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            ENVIRONMENT=production \
            DEBUG=false \
            PYTHONPATH=/home/site/wwwroot \
            WEBSITES_CONTAINER_START_TIME_LIMIT=1800 \
            WEBSITES_PYTHON_DEFAULT_VERSION=3.13 \
            WEBSITES_PYTHON_VERSION=3.13 \
            PYTHONUNBUFFERED=1 \
            PYTHONDONTWRITEBYTECODE=1

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        continue-on-error: false
        timeout-minutes: 20
        with:
          app-name: 'jrc-enquiry-assistant-operations'
          slot-name: 'Production'
          package: '.'
          startup-command: 'bash startup.sh'

      - name: 'Restart Azure App Service'
        run: |
          # Get the resource group name for the web app
          RESOURCE_GROUP=$(az webapp list --query "[?name=='jrc-enquiry-assistant-operations'].resourceGroup" --output tsv)
          
          if [ -z "$RESOURCE_GROUP" ]; then
            echo "Web app 'jrc-enquiry-assistant-operations' not found. Skipping restart."
            exit 0
          fi
          
          echo "Restarting App Service in Resource Group: $RESOURCE_GROUP"
          
          # Restart the app service
          az webapp restart --resource-group $RESOURCE_GROUP --name jrc-enquiry-assistant-operations --slot Production

      - name: 'Verify Deployment'
        run: |
          echo "Deployment completed successfully!"
          echo "App Name: jrc-enquiry-assistant-operations"
          echo "Slot: Production"
          echo "Startup Command: bash startup.sh"
          echo "App Service has been restarted to apply new settings"